name: Trigger auto deployment for limblessgpt

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/limblessgpt-AutoDeployTrigger-dfd65e22-f7e2-4074-b7e4-73f0e500a2cf.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LIMBLESSGPT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: limbots.azurecr.io
          registryUsername: ${{ secrets.LIMBLESSGPT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LIMBLESSGPT_REGISTRY_PASSWORD }}
          containerAppName: limblessgpt
          resourceGroup: Discord_Bots
          imageToBuild: limbots.azurecr.io/limblessgpt:${{ github.sha }}
          

     

